# 승인자 슬랙 UserID
approvers:
  - U0A5RD2NZ1D

# 슬랙 채널 ID
slack_channels:
  transfer_reservation: "C0AANUJGPAB"
  error: "C0AANUJGPAB"

# Spread Sheet ID
# 아래의 URL의 작업 할 시트의 id를 추출해서 작성한다
# https://docs.google.com/spreadsheets/d/{id}
spreadsheet:
  id: "1AS3uLh8rKgHPsjKO_gy6sg1erNjVm_1fOOCPWr458bY"
  sheets:
    settlement: "정산"
    approval_log: "승인로그"
