"""add thread_references table

Revision ID: 22932a982c3f
Revises: 83c070e537ee
Create Date: 2026-02-09 11:12:36.495704

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22932a982c3f"
down_revision: str | Sequence[str] | None = "83c070e537ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_references",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("booking_key", sa.String(length=100), nullable=False),
        sa.Column("channel_id", sa.String(length=50), nullable=False),
        sa.Column("thread_ts", sa.String(length=50), nullable=False),
        sa.Column("root_booking_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_key"),
    )
    op.create_index(
        "idx_thread_refs_booking_key", "thread_references", ["booking_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_thread_refs_booking_key", table_name="thread_references")
    op.drop_table("thread_references")
    # ### end Alembic commands ###
