"""add cancellation_thread_refs table

Revision ID: 8ead2c41c45a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 13:53:21.070182

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ead2c41c45a"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cancellation_thread_refs",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("booking_key", sa.String(length=100), nullable=False),
        sa.Column("channel_id", sa.String(length=50), nullable=False),
        sa.Column("thread_ts", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_key"),
    )
    op.create_index(
        "idx_cancel_thread_refs_booking_key",
        "cancellation_thread_refs",
        ["booking_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_cancel_thread_refs_booking_key", table_name="cancellation_thread_refs"
    )
    op.drop_table("cancellation_thread_refs")
    # ### end Alembic commands ###
