"""AI-075: add seller_channel_cost column

Revision ID: b1c6719de18c
Revises: edfb1f9427c9
Create Date: 2026-03-19 15:55:10.390115

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c6719de18c"
down_revision: str | Sequence[str] | None = "edfb1f9427c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issue_logs", sa.Column("seller_channel_cost", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "settlements", sa.Column("seller_channel_cost", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settlements", "seller_channel_cost")
    op.drop_column("issue_logs", "seller_channel_cost")
    # ### end Alembic commands ###
