"""drop cancellation_thread_refs table

Revision ID: edfb1f9427c9
Revises: 8ead2c41c45a
Create Date: 2026-03-16 15:21:17.776216

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edfb1f9427c9"
down_revision: str | Sequence[str] | None = "8ead2c41c45a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_cancel_thread_refs_booking_key"),
        table_name="cancellation_thread_refs",
    )
    op.drop_table("cancellation_thread_refs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cancellation_thread_refs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("booking_key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("channel_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("thread_ts", sa.VARCHAR(length=50), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_key"),
    )
    op.create_index(
        op.f("idx_cancel_thread_refs_booking_key"),
        "cancellation_thread_refs",
        ["booking_key"],
        unique=1,
    )
    # ### end Alembic commands ###
