"""add transferred_to to settlements

Revision ID: f7a08a3118ab
Revises: 22932a982c3f
Create Date: 2026-02-19 10:40:43.518969

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7a08a3118ab"
down_revision: str | Sequence[str] | None = "22932a982c3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settlements", sa.Column("transferred_to", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settlements", "transferred_to")
    # ### end Alembic commands ###
